import Head from "next/head";
import Image from "next/image";
import NavOpen from "../components/NavOpen";
import { useState } from "react";
import { MenuAlt1Icon } from "@heroicons/react/solid";

export default function Home() {
  const [nav, setNav] = useState(false);
  return (
    <div>
      <Head>
        <title>Xono</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <MenuAlt1Icon
            onClick={(e) => setNav(true)}
            className={`${
              nav && "hidden"
            }  absolute hover:scale-110 hover:text-white transition duration-100 ease-in-out top-0 bottom-0 w-10 my-auto text-white/80 cursor-pointer right-10 `}
          />
        </div>
        {nav && <NavOpen setNav={setNav} nav={nav} />}
      </div>
    </div>
  );
}
